name: firebase_storage_mocks
description: Mocks for Firebase Storage. Use this package to write unit tests involving Firebase Storage.
version: 0.2.0
homepage: http://blog.wafrat.com
repository: https://github.com/atn832/firebase_storage_mocks

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^8.0.0
  mockito: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.16.5
